### ISSUE TITLE
sample request

### ISSUE THREAD

**Issue by issam1975** [Yeah69/BFF.DataVirtualizingCollection#1]
Hi,

this is not an issue but a sample request .

that would be great if you can demonstrate this library with other data controls  than the datagrid .

for example :
i would love to see a sample of a datavirtualized listbox with multiples columns
something like this : https://ibb.co/2kQVxvM

anyway thanks for the hard work .

**Comment by Yeah69** [comment]
Hi,

instead of replying right away I wanted to do the sample at the weekend. However it turns out that I don't have much free time this weekend. So this may take a while.

**Comment by issam1975** [comment]
that's awesome .

thanks for considering doing this <3

**Comment by Yeah69** [comment]
Your sample request is now pushed to master. Its the last tab in the sample app.

First of all, it is programmed in quick-and-dirty manner. I got hooked by the idea to replicate the look and feel of an application such as can be seen in your snippet. However, I don't have the time to do it in such a clean fashion as I would like to. This means: please pick the parts which you need to set up the data virtualization framework for your use case, but be wary of the rest.

Now to the interesting parts!
Let a side that you explicitly didn't want it to be based on a DataGrid, this sample would be difficult to realize with a DataGrid. In my opinion the closest WPF UI-element to the look of the sceenshot would be a WrapPanel or UniformGrid. But it is not an items control, hence you can't bind an ItemsSource to it. So I tried my luck with a ListBox. You can customize the backing items panel for it (I think the default is StackPanel or VirtualizingStackPanel). Unfortunately, just using the WrapPanel doesn't work:
![image](https://user-images.githubusercontent.com/11756150/54465217-5b02c080-477a-11e9-9aeb-72dd07a75e58.png)
I totally recommend you to try it yourself, then you see the consequences. Visually the application will freeze, but the interesting question for us is the reason why it does so. The WrapPanel does not use UI virtualization (only render data which can be seen; recycling UI-elements), so it needs to fetch all the data from the ItemsSource in order to render itself. This is exactly the opposite of what we want to do with data virtualization. We need to avoid that. UI virtualization is a pre-requirement for data virtualization! The only native virtualizing Panel which I know of is the VirtualizingStackPanel. Using it would leave the data virtualization intact, however, it would look like that:
![image](https://user-images.githubusercontent.com/11756150/54465597-3c9dc480-477c-11e9-98a8-bf5ae6c72305.png)
So I searched for a Panel implementation which wraps the elements line by line and has UI-virtualization. I found one: https://www.codeproject.com/Articles/158060/Dan-Crevier-s-VirtualizingTilePanel-Mod. I didn't even look into the code and just used it blindly, it works well for this sample.
If you are okay with a single row which doesn't wrap and is very long a VirtualizigStackPanel with Orientation to Horizontal would be sufficient as well: 
![image](https://user-images.githubusercontent.com/11756150/54465913-cac67a80-477d-11e9-89e0-cb027bc2cbb1.png)

Important remark!
Besides using the WrapPanel. There are other circumstances when WPF triggers to fetch all data of the ItemsSource. For example putting the ListBox into a StackPanel (instead of the 2-row grid which it is in now)  and using a VirtualizingStackPanel with vertical orientation will result in fetching all data. If you try this in the sample you can notice the logs going wild, because every loaded page is logged live.
In my DataGrid use cases I had trouble with rows which increased their height, that situation as well caused the UI to fetch all data.
You have to keep in mind that WPF does not support data virtualization out-of-the-box. Hence there are pitfalls here and there. But in my experience you can find a way to workaround that. And in some cases the effort to work around is worth it.

**Comment by issam1975** [comment]
thanks a lot man for taking time for this .

can't wait to check this out and give feedback .
