### ISSUE TITLE
sample extremely complicated.. DataVirtualization for dummies please?

### ISSUE THREAD

**Issue by WillEhrendreich** [Yeah69/BFF.DataVirtualizingCollection#11]
I cannot make heads or tails of what's going on here. 

the sample is so full of layers of abstraction, I can't keep it all in my head at once. 
![image](https://user-images.githubusercontent.com/55286472/147714624-112c29f9-fbcf-454c-a994-ef3b7609da4e.png)

all i want is to be able to get data virtualization over my observable collection.. why is this so confusing to do? 

I'm so lost. I see the example and my brain sees:
![image](https://user-images.githubusercontent.com/55286472/147714327-024a650a-8091-4513-8109-037dfafc74e0.png)

your hello world example looks like it only works for some huge list of ints, is that whats going on??

Whats happening? 

look, I know that's all probably not the most accurate of assessments of the work you're doing, I can tell that once I have any clue how it's getting any of this accomplished I'll be really happy with it, but please.. please... for the love of all that is good and right and holy.. have mercy on the slow ones among us.. 

please make an example of taking an ObservableCollection<T>() where T is some sort of class with like.. an ID property or something.. and then show how you go from your datagrid looking at that, to your datagrid using your Data Virtualized collectionview instead. 

please as straightforward as possible. 

like I'm five. 

and not a smart five year old either, like.. one you know won't get invited to parties when their older.. 
![image](https://user-images.githubusercontent.com/55286472/147714675-b15c5d72-9b1f-4b09-803e-1e883b57ec9f.png)

**Comment by Yeah69** [comment]
Hi,

first of all, I like your humor. A lot of creativity must have gone into this issue. I especially like the snippet with the code. It hits the nail on the head in a satirical way.

I see and understand the criticism. This project is certainly not beginner friendly yet. So my suggestion is that I post a "Getting Started" to the wiki as soon as possible and let you know here once it's ready. I may also make another sample that is much simpler and more concrete and better suited to be a starting point.

Here are a few points that might help you a bit:
- The collections of this project do not use `ObsevableCollection`s directly. They implement the same interfaces as the `ObservableCollection` (especially `IReadOnlyList<T>` & `INotifyCollectionChanged`). So they are meant as a replacement for `ObsevableCollection`s. Data virtualization means that only the data that is needed or displayed is loaded. An `ObservableCollection` has all its items loaded in memory at all times. This is exactly what we want to avoid with data virtualization. So we can't use them directly.

- The sample project in its current form is intended more as a desktop app to inspect the settings options. That's why it is designed very dynamically in code. In fact, for concrete applications, one would decide on certain settings and stick with them. Thus, the code of the current samples is really not suitable for one-to-one adoption. That's why the simpler sample in my proposal. I will also name it accordingly what which sample is meant for. 

Lastly, thanks for getting in touch. When I've been working on a topic for so long, it's hard for me to figure out what would be most relevant for beginners.

**Comment by WillEhrendreich** [comment]
Thanks for taking it how it was meant, I was partially worried my tone wouldn't come off correctly, I really did mean to make someone smile while reading it. 

I would certainly love what you suggest, for sure. 

I'm currently actually using a modified SynchronizedCollection that I've subclassed and shoehorned a bunch of ObservableCollection on top of, as well as some easier to use quality of life type of methods to interface with the default collectionview, which is also currently changed to a wrapper of listcollectionview that is deferring update notifications. 

the solution is perhaps not an elegant one, but that's why im looking to use your library. 

thanks for your help!

**Comment by Yeah69** [comment]
Here is a beginner's guide that I created just now: https://github.com/Yeah69/BFF.DataVirtualizingCollection/wiki/Beginner's-Guide
And also a few days ago I implemented a minimalistic getting started sample which has far less abstractions: https://github.com/Yeah69/BFF.DataVirtualizingCollection/blob/main/Sample.GettingStarted/MainWindow.xaml.cs

I hope that with those my project is easier to understand.

Based on your descriptions it seems to me that your approach is closer to the UI (View-layer; tinkering with the CollectionView). My approach is rather located at the ViewModel-layer with the UI being oblivious about it (because they just use IList, INotifyPropertyChanged and INotifyCollectionChanged). During development of the my approach it also has crossed my mind whether to tinker with the (List)CollectionViews and other UI elements, but I never did for a few reasons:

- I would need to work myself into alot of more internals of WPF
- From my experience it is almost always a struggle if deviating from the defaults of the intended ways of the UI frameworks <== So I wanted to keep that at a minimum
- The whole chain from data source to View needs to be virtualized anyway. If the thing that you have in between data source and the View loads all items from the data source just to virtualize some of them right before UI, then there isn't won much in my opinion
- Depending on WPF's CollectionView would mean depending WPF itself which in turn would definitely exclude everything else. I didn't try, but it wouldn't surprise me if this project would work with UWP, Avalonia, Mono, MAUI and so on. Because from what I know of they all support the same interfaces. At least UWP has even better support for data virtualization as it has optional interfaces which are made specifically data virtualization: https://docs.microsoft.com/en-us/windows/uwp/debug-test-perf/listview-and-gridview-data-optimization#random-access-data-virtualization . I am eager to play around with those interfaces. But I have very little interest in UWP as a whole, so that demotivates me.

**Comment by WillEhrendreich** [comment]
Can't wait to dig in! 

Thanks so much for your efforts, and for taking my issue in the spirit I meant it, I was hoping the playfulness came across correctly! 

I will take a look at the sample, and get back when I can, but I've found out that the biggest issue is not the data, it was the fact that I was trying to use super heavy MaterialDesignInXaml styling in my datagrid, which, as you can guess, did not go as well as planned. 

The library is great, and does a great job if you're not trying to abuse it, but my inexperience in UI creation (this is my first real project) and the relatively small barrier to entry to getting started with that library led me to a false sense of security. 

gigs.. and gigs.. of memory.. for a grid with 1400 rows. 

Anyway, all of that is to say that I discovered that I was trying to use data virtualization as a band-aid when, really, the more critical issue is to make sure I don't shove gigs of UI allocations down the app's throat.. 

I still think there's likely a place for data virtualization with my application, I just think that it's gone from the most important thing to a "After I fry the bigger fish" issue for the time being. 

Again, Thank you so much for responding and helping, It's fantastic. I'll just close the issue, and call it good, and if I happen to run into any more challenges, I'll open another issue with specific questions.

**Comment by WillEhrendreich** [comment]
Ok, that beginner's guide is badass. I understand the basics of what is needed for this to work. THANK YOU~!!

**Comment by Yeah69** [comment]
You're welcome. And I am glad that I could've helped. Feel free to open new issues, if new questions come up.

I hope you'll get your case, where data virtualization might help, resolved. ;)
