### ISSUE TITLE
[Question] Any plan to improve the Page-Holding?

### ISSUE THREAD

**Issue by gigios** [Yeah69/BFF.DataVirtualizingCollection#2]
I like your implementation of Virtualizing Data, but, for a my project, it's not possible to use the current implementation because does not discharge the pages when are not used!

There are any plan to improve the current Page-Holding mechanism with a new 'strategy' that reuse memory?

**Comment by Yeah69** [comment]
@gigios Sure, I had some ideas, but for me the hoarding strategy was sufficient sofar, so I continued to work on the project which uses this data-virtualizing library.
However, knowing that others are using this library and that other strategies are demanded is a great motivation to get back here.
I am currently at work, but I'll get back to this topic this weekend. Thank you for opening this issue :)

**Comment by Yeah69** [comment]
@gigios Hi,
I looked into that in the weekend and have concept in mind. I have also started to implement, but unfortunately I didn't finish it in last weekends time.

Sofar my plan is to implement the "Least Recently Used"-strategy (i.e. if necessary the least recently used page is dismissed) where the calling side has to provide the page limit. Additionally, I am going to implement the possibility to provide their own page replacement strategies for the users. Hence, if everything worksout as expected, then there'll be an interface to implement your own strategy against so you can inject it into the data-virtualizing collection.

I'm eager to include other strategies which make sense in general later on. The function for injection custom page-replacement strategies will provide a way to also use highly specialized strategies.

Will the "Least Recently Used"-strategy be sufficient for your requirements? Or would you need another strategy?

Another topic are `IDisposable`s. In scope of this issue my plans at the moment are to automatically dispose the disposables of page which are dismissed. This is consistent to the behavior sofar, because if you dispose the data-virtualizing collection itself then it is going to dispose all currently hold disposables.
My intention is to implement a setting in future which switches of the disposal behavior in general. Would that be one of your requirements?

**Comment by gigios** [comment]
@Yeah69 Hi,
First of all thanks for the answer and for the investigation of a new solution.
I think your first solution is, for now, perfect (also about the IDisposable mechanism). 
My first requirement is to reduce the memory usage, and probably your solution it's perfect!
I like also your idea to allow the user to 'extend' the possibility of this behavior!

Additional question (I don't have tested for the moment and not related directly this improvement):
I need to manage also new data to add to the collection. Is it possible in the current implementation without big problems in the UI? (sorry for this additional request)

**Comment by Yeah69** [comment]
@gigios Thank you for the feedback!

The data-virtualizing collection (from now on I'll abbreviate DVC) itself doesn't support functions like insert, add or remove and so on, because it doesn't make any assumptions about the backend you use. You just need to provide a function which fetches the total count of the elements and a function which gets a page of elements on demand (I call that functions fetchers). The DVC doesn't get any other information. It has no way to add or remove any element. Furthermore, the DVC has no way to know when the backend changed. All these are not the responsibilities which the DVC assigns to itself.

However, in my hobby project BFF I do additions and removal of elements outside of the DVC. I use a SqLite backend. Whenever I do an operation which alters the data-virtualized SqLite table, I just dispose the old DVC and create a new one as a replacement. The new one will then fetch the pages with the updates included. The benefit of data-virtualizing is that it doesn't matter how big your virtualized data set is, you can dispose the old one anytime and replace it with a new one. The new one will only load the data it needs at the moment of replacement. You can see my approach to this in my [hobby project BFF](https://github.com/Yeah69/BFF).

Be aware if you use WPF as a frontend. It doesn't support data virtualization well and has some pitfalls and restrictions which require special care. In BFF I implemented a set of workarounds, but managed to integrate the DVC as `ItemsSource` for a `DataGrid`. If you run into these pitfalls you can ask me.

**Comment by gigios** [comment]
@Yeah69 Thanks again for the answer.
I'm using WPF and my idea is to use your DVC library to manage the virtualization in a ListView, the problem (but probably it's not a real problem) it that the I must manage additional data (insert at top of my ListView, in a similar way of an email application when coming new emails).
Probably, as you have suggested, the best solution is to reload the data.

**Comment by Yeah69** [comment]
@gigios I have pushed the implementation of the new least recently used (LRU) page removal strategy. As well as the custom way to create own page removal strategies.

The LRU requires the parameter `pageLimit` and has an optional parameter `removalCount` (if not set explicitly its default is 1). As soon as a page is requested which leads to overflowing the `pageLimit` the LRU request page removals of the least recently used page. The count of the pages requested for the removal will force the page store to keep only "`pageLimit` - `removalCount`" pages. Hence you could use the `removalCount` as a buffering function. For example, if you set the `pageLimit` to ten and the `removalCount` to five then the eleventh page will lead to five page removal so there will be a buffer of four pages until the next overflow.
But you can keep the `removalCount` at one, then after the eleventh page load all further page loads will lead to a page  removal.

For the custom was you just need to implement a lambda function. The only Parameter is an `IObservable<(int PageKey, int PageIndex)>` which is an event stream of element requests. `PageKey` is the index of the page in the page store and `PageIndex` is the index of the element inside of the page. That way you can track all element requests. Your lambda should return an `IObservable<IReadOnlyList<int>>` which is an event stream of page keys which should be removed. I implemented the LRU that way, so I am sure that this will work. However, the custom way is the expert mode, I recommend to look into the code of this project before you use it.

**Comment by gigios** [comment]
@Yeah69 Thanks for this new 'very welcome' implementation!
