### ISSUE TITLE
[Question] How to manage data that is continuously increasing?

### ISSUE THREAD

**Issue by gigios** [Yeah69/BFF.DataVirtualizingCollection#3]
Hi, I went back to try this library and I immediately have a new question.
I have a database that is updated continuously (the records increase every second).
I need to show these values in a ListView but I want to manage the data, if it's possible, with your library.
The data are shown starting from the newer to the older, for this reason I have a timer that check the DB for the new data and load only these in memory, after add these new items to the collection in binding with the ListView (insert the data at the 0 position).

Is it possible to manage these collection with your library?
If the answer is yes, how I can manage the data (update the count, update the selected index/offset)?

**Comment by Yeah69** [comment]
Hi, 

first of all, I am sorry for the late response. But I worked on new stuff (v2.0.0) for this library and hope it is worthwhile.

Second of all, I appreciate it big time that you are keep on trying to use my library. Thank you.

Now responding to the question:
There are two approaches. One which should work with all versions and another only for v.2.0.0+ versions.

Pre v2.0.0:
Each time that you know that  the backend changed

1.  Your view should memorize the scroll position
2.  Dispose the current data virtualizating collection => the assumption is that any item could be out of date.
3.  Build a new data virtualizing collection the same way as the previous. Replace the old one with the new one
4.  Notify that the property of the data virtualizing collection has changed
5.   In your View jump back to the memorized scroll position

This is coarsely outlined the procedure I used up until v2.0.0. For points 1. & 5. I used events ("PreVirtualizationUpdate"/"PostVirtualizationUpdate") on ViewModel-side and exploited them in code behind of the View-side. So you can imagine that it is a pretty messy workaround. But still for a long time I was happy to get the data virtualization working.
The updates in my application are triggered by the user, hence not as frequent as in your scenario. But I guess it could still work.

Post v2.0.0:
The data virtualizing collection has now a function called "Reset". When triggered it pretty much does the procedure described in "Pre v2.0.0" for you. Without the scroll position memorization of course, but it shouldn't be necessary, because with "Reset" the Count-property of the data virtualizing collection should never jump to 0.
I would advise you to try this approach at first, because it should cause you much less overhead than the first. However, "Refresh" is still a new feature and it may be not as stable as the first approach.

I think v2.0.0 has a breaking change (switched order of the builder "decisions" and removed one obselete function), but it shouldn't be critical ones. 
Besides that I implemented an alternative to the data virtualizing collection: the sliding window. It is even more specialized but handy for specific use cases which I have in my application. Please feel free to have a look at the sliding window. I would like to get your feedback on that.

**Comment by gigios** [comment]
Hi,

thanks for the answer.
For the moment I have found a bottleneck in my code and, having solved this problem, I am able to manage the data even without pagination (for the moment, obviously, when the data will increase a lot, probably the next step will be the pagination).
I like your library, not used very often on my side but I like it.
I can't promise you to try version 2 in a short time, but I'll definitely do it.

Thanks again for the support and for your library!
