### ISSUE TITLE
foreach is not working for me

### ISSUE THREAD

**Issue by metheofanis** [Yeah69/BFF.DataVirtualizingCollection#4]
I've noticed that foreach is not working as expected. Do I miss something?

How to reproduce:
Add the following code in BFF.DataVirtualizingCollection.Sample in MainWindow.xaml.cs at the end of the constructor:
```         
            Debug.WriteLine(MillionNumbers.Count());
            foreach (var item in MillionNumbers)
            {
                Debug.WriteLine(item);
            }
```
The `Debug.WriteLine(MillionNumbers.Count());` shows correctly 1000000 but it is not entering foreach loop. It looks like `GetEnumerator()` in `DataVirtualizingCollectionBase.cs` is giving null.
Please advice.

**Comment by Yeah69** [comment]
The GetEnumerator()-Function just returns the enumerator of an empty enumerable. 

![image](https://user-images.githubusercontent.com/11756150/77253477-de42d600-6c5a-11ea-8732-bb3901ed9d2b.png)

Currently, there is no support for enumeration and therefore no support for foreach-loops. However the indexer should work just fine, hence a for-loop should work. Still, iterating the collection with loops (doesn't matter which exactly) is not the use case for the data virtualizing collection, because it would be approximately like fetching all the data at once. If you need all the data at once the pagination of the data virtualizing collection could even have a worse performance than just fetching all data in one run.

My use cases so far were to represent a big amount of data (for example, a big table from a database or all months of DateTime) or object with a great payload (which you don't want to instantiate all at once) in an WPF application. Fortunately, the WPF-Controls like DataGrid or ListBox seem to use the indexer instead of the enumerator.

That all said, I don't think that there should be a technical issue in enabling enumeration. Maybe the data virtualizing collection can have benefits used with loops. So far I just hadn't such a use case in mind. I am curious, do you have such a use case in mind?

I'll enable the enumeration soon and push it here and update the nuget-package. 
If you cannot wait, then you could implement it in GetEnumerator() in DataVirtualizingCollectionBase with a for-loop iterating over all indices using GetIndexInner(...). I would strongly recommend to use sync index access, because the async index access would return placeholders instantly and waiting for the real element could get messy very quick.

**Comment by metheofanis** [comment]
I understand what you have said.
I'm using [this](https://github.com/HandyOrg/HandyControl/tree/master/src/Shared/HandyControl_Shared/Controls/Cover/CoverView) control to show book covers. I could not see any results. Empty. I found that it is using internally a foreach loop. So I guess the problem is that this control doesn't support UI virtualization.
I'll be waiting for your implementation. 
Thank you very much!

**Comment by Yeah69** [comment]
I implemented the iteration of the data virtualizing collection with version v2.0.0.

I did take a look into the linked controls library HandyControl. Interestingly, the problem is that CoverView inherits from the WPF class Control and not the WPF class ItemsControl (which itself inherits from Control and is more suited for displaying collections of items). ItemsControl introduces the ability to customize the backing panel. Thus, with ItemsControl you can switch from the default Panel to the VirtualizingStackPanel (our hero!). However, CoverView doesn't provide such a customization feature and doesn't use the VirtualizingStackPanel per default.
So I think you are right, CoverView doesn't support UI virtualization. Unfortunatly (for this case), UI vritualization is a pre-requirement of the data virtualizing collection.

That all said, I think you could use my new alternative to the data virtualizing collection: the sliding window (from v2.0.0). The special thing of the sliding window is that it crops a very small section section of the backend (as small as the chosen window width) and therefore doesn't require UI virtualization. You could choose a window width as big as many covers you want to display at once. And for scrolling through all backed covers you'll need two buttons which will trigger a slide left or a slide right. If you choose to use the sliding window I would appreciate your feedback.

I also tried to use the CoverView in my sample application, but unfortunately I didn't get it to work until now. Maybe I'll try again. If I get it working I'll push a commit ;)

**Comment by Yeah69** [comment]
Okay, I got a sample project which shows the CoverView on branch develop. You can build and start the project BFF.DataVirtualizingCollection.Sample.HandyControl. Seems like HandyControl requires the .Net Framework. The other sample project is .Net Core. So I had to create a new project.
The sample is nothing fancy, but I think it will be enough to show you how I would imagine to use the sliding window for the CoverView. It works but still ist buggy as soon as you start sliding.
I don't know yet whether it is a bug in BFF.DataVirtualizingCollection or HandyControl. But I think I'll look into it further.
Good thing that you animated me to create the sample for the  sliding window. Instantly found bugs which I'll have to fix. :D

**Comment by metheofanis** [comment]
Thank you so much.
I'll check everything you've said to educate myself.
By the way, I've opened an [issue](https://github.com/HandyOrg/HandyControl/issues/340) in HandyControl asking UI virtualization. But I'm too novice to suggest any solution. I thought maybe it is good idea if you could suggest!
Really appreciate.
Regards.

**Comment by Yeah69** [comment]
Okay.

I still think that the new sliding window could be useful here, because it hasn't to rely on UI virtualization. I pushed some bug fixes for the sliding window. Now it should be pretty stable with standard WPF items controls.
But the CoverView of HandyControl still has some strange behavior with it. Have a look at the sample of BFF.DataVirtualizingCollection.Sample.HandyControl. There you can see the CoverView and a ListBox side by side for comparison. Both get the ItemsSource bound to the same sliding window instance. The ListBox works exactly as intended, the CoverView seems buggy.

I'll participate in the conversation of your issue. I am curious about that myself. ;)
