### ISSUE TITLE
Add/Remove plans?

### ISSUE THREAD

**Issue by metheofanis** [Yeah69/BFF.DataVirtualizingCollection#5]
Hello,
Any plans to implement Add/Remove any time soon?
Thanks.

**Comment by Yeah69** [comment]
Hello,

the short answer is No.

The library BFF.DataVirtualizingCollection is intended to work on top of a big backend. It provides pagination. Change management like Inserts/Additions/Remove/Deletion is delegated to the user of this library (in your case you).
I am open to discuss features which make it easier to react to changes in the backend. With v2.0.0 I introduced the Reset-function (see my response of issue #3 ).

In conclusion, the main intention of BFF.DataVirtualizingCollection is to make the incremental loading (pagination) of a huge backends data possible and easy. I am happy to improve the "making it easy to use" part, but I will not support Add/Remove in the foreseeable future (probably never). 

I even experimented to let the data virtualizing collection only implement the interface IReadOnlyList instead of the IList interface. But it won't work with WPF and here is why (in my opinion pretty interesting):
The items controls of WPF try to work with the ungeneric IList. They cannot use generic IList<T>, because the controls themselfs are ungeneric and the binding engine of WPF has to work loosely coupled. Thus, if the bound collection type doesn't implement the ungeneric IList, then the control will fall back to the IEnumerable interface. Effectively they cannot use the indexer now and are required to iterate the whole collection in order to show the last. Of course, with data virtualization you want to avoid iterating the whole collection to show the last item and instead just load the last page. So an indexer is required but the IReadOnlyList<T> has an indexer. Why not just use it, right? The answer of my investigations is, because there is no ungeneric IReadOnlyList. Hence (remember the ungeneric controls and loose coupling), we need IList just to get the indexer.
I think there is no ungeneric IReadOnlyList, because IReadOnlyList<T> was introduced after C# got generics so the .Net developers hardly saw a reason for a ungeneric variant.

Thats why the data virtualizing collection is implementing Add/Remove by throwing NotSupportedExceptions.

**Comment by metheofanis** [comment]
Thank you for your valuable detail explanation.
Could you advise a little bit?
I'm using entityframework core and SQLite database.
So you suggest adding (for example) the new entry directly to the database? Then the DataVirtualizingCollection will "see" it when it passes over?
What about deleting? If the user deletes the selected entry?
Maybe you mean to take the source code of  DataVirtualizingCollection and implement it myself? That would make sense!
Thanks again.

**Comment by Yeah69** [comment]
Up until now I used Dapper for Sqlite. I don't know much of EF Core besides that it is a heavy-weight ORM in comparison to the micro ORM Dapper. If there is a way in EF Core to load subsequent entries (I call them pages) with arbitrary offset and lengths than it is good to go with BFF.DataVirtualizingCollection.
When you build a data virtualizing collection you need to specify a function for loading a page and a function for getting the count of entries of the virtualized backend. I call this functions the page- and the count-fetcher, respectively. These fetchers should always pull the data from the backend in its current state.
As soon as you update your backend in anyway these fetcher will from that moment load the current updated data **if** (!!) they are triggered. However, the data virtualizing collection doesn't track changes to your backend, hence it doesn't trigger reloading the data on its own.
Therefore, I implemented the Reset-function on the interface IDataVirtualizingCollection. If you trigger Reset after you made changes to you backend then the data virtualizing collection should reload itself.

BFF.DataVirtualizingCollection is open source feel free to do with it whatever you like (except evil stuff; please don't do evil stuff ;) ). My aim is to get the data virtualizing collection to be as comfortably usable as possible. I provide a nuget package. So it should be sufficient to just pull the package and use it.

I would recommend you to have a look at the sample projects. There you can see how to use BFF.DataVirtualizingCollection. Unfortunately, I don't have a sample where you can add to or remove the backend and refresh.

**Comment by metheofanis** [comment]
FYI: I've already tested with entityframework core and DataGrid Control. It is working perfectly. (For read-only). I'll try to implement add/remove for my specific project.
Dapper sounds interesting. I wish I'll find some time to examine.
Thanks for your advice and information!

**Comment by Yeah69** [comment]
Hello again.

I have created a wiki that should now answer the original question of this issue. Especially for this issue [this article](https://github.com/Yeah69/BFF.DataVirtualizingCollection/wiki/Break-in-Liskov's-Substitution-Principle) should be relevant.

Feel free to read the whole wiki. If something is missing or unclear, let me know via a new issue. I close this issue.
