### ISSUE TITLE
Add override TaskBasedFetchers

### ISSUE THREAD

**Issue by kronic** [Yeah69/BFF.DataVirtualizingCollection#8]
Add override methods
```csharp
public IAsyncOnlyIndexAccessBehaviorCollectionBuilder<TItem, TVirtualizationKind> TaskBasedFetchers(
      Func<int, int, CancellationToken, IAsyncEnumerable<TItem>> pageFetcherAsync,
      Func<CancellationToken, Task<int>> countFetcherAsync)
{
}

public IIndexAccessBehaviorCollectionBuilder<TItem, TVirtualizationKind> NonTaskBasedFetchers(
      Func<int, int, IEnumerableT<Item>> pageFetcher,
      Func<int> countFetcher)
{
}
```

**Comment by Yeah69** [comment]
Hi kronic,

I like the idea to provide `CancellationToken`s to the fetcher functions. I'll try to implement it coming weekend, because I am busy at work these days.

**Comment by kronic** [comment]
@Yeah69 I looked at the code there a lot, you need to change for correct implementation

**Comment by Yeah69** [comment]
@kronic challenge accepted. ;)

**Comment by Yeah69** [comment]
@kronic https://www.nuget.org/packages/BFF.DataVirtualizingCollection/3.3.1
This update now has `CancellationToken` and `IAsyncEnumerable` support.
Please have a look into it and give me feedback whether it works as expected. I hadn't have much experience with both of these.
At least I extended the sample app so I could test the `IAsyncEnumerable`. There it looked fine to me.

```
public IIndexAccessBehaviorCollectionBuilder<TItem, TVirtualizationKind> NonTaskBasedFetchers(
      Func<int, int, IEnumerableT<Item>> pageFetcher,
      Func<int> countFetcher)
{
}
```

A bit more information on that one would be nice. I am pretty sure that you would figure out yourself that if you have an enumerable you could always just call `ToArray()` in order to fulfill the overloads with array outputs.
So my guess would be that you would like this overload to pull from the `IEnumerable` one by one from the background scheduler (like I did now with the `IAsyncEnumerable`) and notify one by one.
I'll give some thought about that and try to answer tommorrow.

As a side note: I am thinking about replacing the array output types with `IReadOnlyList<T>`. That way the user may output arrays and lists. It also should be backwards compatible, because arrays implement that interface. I'll check whether I could do that without additional overloads.

**Comment by Yeah69** [comment]
@kronic I'm not convinced that `IEnumerable<TItem>` overloading technically fits the concepts of `BFF.DataVirtualizingCollection`. For the following reasons. `BFF.DVC` distinguishes between synchronous and asynchronous indexer access. An important difference between the two ways is that in the asynchronous way placeholders have to be generated (because as long as the right elements are loaded something else has to be displayed so that the program flow is not interrupted) and in the synchronous way placeholders are not necessary because there is simply synchronous waiting.
The `IEnumerable<TItem>` overload only makes sense for the synchronous way, because on the asynchronous side we have the `IAsyncEnumerable<TItem>` variant for it from now on (thanks for the suggestion). If I had to guess, I'd say you knew that because your suggestion for the `IEnumerable<TItem>` overload is missing the `CancellationToken`s (which of course don't do anything synchronously because it never cancels).
So. An `IEnumerable<TItem>` overload with issuing single elements (instead of whole pages at once) contradicts the synchronous way. In order to issue single elements via the indexer in advance, you have to move the loading of the rest of the elements to the background. By shifting to the background, one would have to wait blockingly for indexer accesses to elements that have not yet been loaded. This bears the danger of deadlocks. To avoid this we would need placeholders. As soon as we have to use placeholders, we are basically on the asynchronous path.

Users of `BFF.DVC` and an `IEnumerable<TItem>` output now have two options.
First option, one turns `IEnumerable<TItem>` into an `IAsyncEnumerable<TItem>` output and defines a placeholder factory (I think this is easy to do). That is, you go the asynchronous way, but the elements are output individually.
Second option, you turn `IEnumerable<TItem>` into an array (or soon maybe an `IReadOnlyList<TItem>`). Then it's the synchronous way, but the elements of a page are output in one go.

The `BFF.DVC` could of course provide an overload with `IEnumerable<TItem>` output and call `ToArray()` itself, but that wouldn't gain the user much and it would be inconsistent with the behavior from the `IAsyncEnumerable<TItem>` output. `IEnumerable<TItem>` just suggests a sequence of items and an `Array`/`IReadOnlyList<TItem>` suggests a bunch of items.

Of course, it's also possible that I'm missing something that could make an `IEnumerable<TItem>` overload possible. I am open for possible solutions.

**Comment by kronic** [comment]
I`m agree
